### PR TITLE
Fix gsp/forecast/all data not loading in past

### LINKED ISSUE #563: Map not loading in the past
Map not loading in the past
Could be due to api upgrade
No new API call when loading past api

### PR DESCRIPTION
**Pull request by braddf**
# Pull Request

## Description

Reimplement the default behaviour of loading all of the GSP forecast history once on page load, by including a start time of the beginning of the default forecast period to the API request to fit the new API behaviour.

> N.B. This will be superseded by the new "cross-sectional" data fetching behaviour to reduce unnecessary data loading

Fixes #563 

## How Has This Been Tested?

- [x] Locally

- [x] _If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: apps/nowcasting-app/pages/index.tsx [hunk 1]
```diff
@@ -237,26 +253,24 @@ export default function Home({ dashboardModeServer }: { dashboardModeServer: str
...
     isValidating: allGspForecastHistoricValidating,
     error: allGspForecastHistoricError
   } = useLoadDataFromApi<components["schemas"]["OneDatetimeManyForecastValues"][]>(
-    `${API_PREFIX}/solar/GB/gsp/forecast/all/?historic=true&compact=true&end_datetime_utc=${encodeURIComponent(
-      `${forecastLastFetch30MinISO.slice(0, 19)}+00:00`
-    )}`,
+    `${API_PREFIX}/solar/GB/gsp/forecast/all/?historic=true&compact=true&start_datetime_utc=${encodeURIComponent(
+      `${forecastFrom.slice(0, 19)}+00:00`
+    )}&end_datetime_utc=${encodeURIComponent(`${forecastLastFetch30MinISO.slice(0, 19)}+00:00`)}`,
     {
```
Comment (peterdudfield) [inline apps/nowcasting-app/pages/index.tsx:266]: could you add a comment that the `+00:00` is for the timezone? I miss read this first as `HH:MM`
