### PR TITLE
✨ Quartz Solar v0.6.2 → Staging (Error Handling & New User Validation Page)

### LINKED ISSUE #571: Bug: if forecast/all doesnt work, dont fail all UI
Currently if forecast/all deosnt work, then the rest of the UI stops working. 
WOuld be good to make this not happen, so national is still visible

### LINKED ISSUE #595: Improve New User Sign Up email

### PR DESCRIPTION
**Pull request by braddf**
# Pull Request

## Description

Improve error handling, removing the incongruous red toast alerts in favour of a more subtle error status.
Also add new landing page for post email sign-up to replace stock ugly Auth0 one, and a "Trial Expired" page for blocked users in Auth0.

Fixes #571 
Fixes #595 

## How Has This Been Tested?

- [x] Locally
- [x] Development: https://dev.quartz.solar

#### New User Flow
image
image
image

#### Error Handling
image

#### New User Flow
image
image
image
image
image

#### Error Handling
image

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by peterdudfield — APPROVED** [review]
Looks fine from me, im sure have but good to test the new user work flow. 

Also there's a few comments from co-pilot that i think look sensible to do before merging

File: apps/nowcasting-app/pages/expired.tsx [hunk 1]
```diff
@@ -0,0 +1,64 @@
+"use client";
```
Comment (peterdudfield) [inline apps/nowcasting-app/pages/expired.tsx]: What does "use client" mean here?
