### PR TITLE
Reset aggregation to GSP when switching to Delta view

### LINKED ISSUE #622: Bug: Delta view gsp select sets Integer if in DNO mode
## To Reproduce
1. Select DNO-level aggregation on PV Forecast map
2. Go to Delta view
3. Select a GSP
4. chart has an integer id as title, and loads forever

## Expected Behaviour / Potential Fix

Reset the aggregation level to GSP when switching to Delta view

### PR DESCRIPTION
**Pull request by braddf**
# Pull Request

## Description

Reset aggregation to GSP when switching to Delta view.

Fixes #622 

## How Has This Been Tested?

- [x] Locally
- [x] Vercel Preview branch: https://nowcasting-app-git-hotfix-dno-delta-select-bug-openclimatefix.vercel.app/

Current dev:
Google Chrome 2025-07-15 10 48 53

Preview:
image

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: apps/nowcasting-app/pages/index.tsx [hunk 1]
```diff
@@ -112,11 +114,15 @@ export default function Home({ dashboardModeServer }: { dashboardModeServer: str
     setArraySettingInCookieStorage(CookieStorageKeys.VISIBLE_LINES, visibleLines);
   }, [visibleLines]);
 
-  // On view change, unset the clicked "GSP" if the aggregation is not GSP
+  // On view change, unset the clicked GSP if the aggregation is not GSP,
```
Comment (peterdudfield) [inline apps/nowcasting-app/pages/index.tsx:117]: should this comment be `unset the clicked region...` rather than `unset the clicked GSP ...`

**Review by peterdudfield — APPROVED** [review]
Looks good. I went on the vercel preview to see behaviour.
